### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by czesiu** [wind-rider/broadlink-dotnet#3]
Hi,

You have TODO in this line about conflict in protocol documentation and python implementation: https://github.com/wind-rider/broadlink-dotnet/blob/7524098dbe71c5e67098f9dd917c2da5d31ba6ac/Broadlink.Net/PacketGenerator.cs#L78

Where I can find this documentation? Could you place link here or send it to me: grzesiek_czesio@o2.pl?

**Comment by hansmbakker** [comment]
https://github.com/mjg59/python-broadlink/blob/master/protocol.md
